version: '3'
services:
  db:
    image: postgres:13
    volumes:
      - odoo_db:/var/lib/postgresql/data/pgdata
    ports:
      - 5432/tcp
    environment:
    - POSTGRES_PASSWORD=odoo
    - POSTGRES_USER=odoo
    - POSTGRES_DB=postgres
    - PGDATA=/var/lib/postgresql/data/pgdata
  odoo:
    build:
      context: .
    command: bash -c "ODOO_QUEUE_JOB_PORT=8069 odoo -i base --load=web,queue_job,attachment_s3 --log-level=debug --addons-path=/mnt/addons,/mnt/extra_addons/odoo-cloud-platform-14.0,/mnt/extra_addons/queue-14.0,/mnt/addons/OdooEduERP-14.0 -d trungth"
    depends_on:
      - db
      - opa
      - mail
    ports:
      - "8069:8069/tcp"
      - "8072:8072/tcp"
    volumes:
      - odoo_data_2:/var/lib/odoo
      - ./config/odoo.conf:/etc/odoo/odoo.conf
      - ./addons:/mnt/addons
      - ./extra_addons:/mnt/extra_addons
  opa:
    image: openpolicyagent/opa
    command: run --server --log-level debug
    ports:
      - "8181:8181"

  hasura_db:
    image: postgres:13
    volumes:
      - hasura_db:/var/lib/postgresql/data/pgdata
    ports:
      - 5432/tcp
    environment:
    - POSTGRES_PASSWORD=odoo
    - POSTGRES_USER=odoo
    - POSTGRES_DB=postgres
    - PGDATA=/var/lib/postgresql/data/pgdata

  graphql-engine:
    image: hasura/graphql-engine:v1.4.0-alpha.1
    ports:
      - "8080:8080"
    depends_on:
      - hasura_db
      - odoo
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://odoo:odoo@hasura_db:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: admin_secret

  pgweb:
    image: sosedoff/pgweb
    ports:
      - 8018:8018
    environment:
      - DATABASE_URL=postgres://odoo:odoo@db:5432/postgres?sslmode=disable
    depends_on:
      - db
      - hasura_db

  mail:
    image: mailhog/mailhog
    volumes:
      - mail_data:/var/log/mailhog
    environment:
      # https://github.com/mailhog/MailHog/blob/master/docs/CONFIG.md
      - MH_SMTP_BIND_ADDR=0.0.0.0:25
      - MH_HOSTNAME=mail
    ports:
      - "1025:25"
      - "8025:8025"
volumes:
  odoo_db:
    driver: local
  odoo_data_2:
    driver: local
  hasura_db:
    driver: local
  mail_data:
    driver: local
