FROM checkraiser/odoo-14.0.1.2
USER root
ENV DEBIAN_FRONTEND noninteractive
COPY requirements.txt /tmp
RUN python3 -m pip install -r /tmp/requirements.txt
COPY ./config/odoo.dev.conf /etc/odoo/odoo.conf
RUN mkdir -p /mnt/addons 
RUN mkdir -p /mnt/extra_addons
ADD ./addons /mnt/addons
ADD ./extra_addons /mnt/extra_addons
USER odoo
