version: '3'
services:
  db:
    image: postgres:13
    volumes:
      - test-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432/tcp
    environment:
    - POSTGRES_PASSWORD=odoo
    - POSTGRES_USER=odoo
    - POSTGRES_DB=postgres
    - PGDATA=/var/lib/postgresql/data/pgdata
  test:
    build:
      context: .
    command: bash -c "odoo --workers 0 -i base,hpu_api -u hpu_api  --addons-path=/mnt/addons,/mnt/extra_addons,/mnt/addons/OdooEduERP-14.0,/mnt/extra_addons/queue-14.0,/mnt/extra_addons/odoo-cloud-platform-14.0,/mnt/extra_addons/rest-framework-14.0 --without-demo=all --test-enable  --test-tags hpu_api --xmlrpc-port=8012 --log-level=test --stop-after-init -d test_2"
    depends_on:
      - db
    ports:
      - "8069"
    volumes:
      - test-web-data:/var/lib/odoo
      - ./config/odoo.test.conf:/etc/odoo/odoo.conf
      - ./addons:/mnt/addons
      - ./extra_addons:/mnt/extra_addons
volumes:
  test-db-data:
    driver: local
  test-web-data:
    driver: local
